import { css } from '@/styled-system/css'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Free Response Checker',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <div
          className={css({
            maxW: 500,
            mx: 'auto',
            px: '4',
            mt: '8',
          })}
        >
          {children}
        </div>
      </body>
    </html>
  )
}
